### PR TITLE
Allow access to attributes for class extensions

### PR DESCRIPTION
**Pull request by Yuav**

### CODE REVIEW

**Comment by TobiasHauck** [comment]
Hi Yoav, thanks for contributing. Why exactly do you want to allow access to all of these attributes? Can you explain me your use case please?

I want to open everything that helps you to customize the driver, but also protect yourself from damaging changes by overriding internal state.

**Comment by Yuav** [comment]
I wanted to extend it. Basically I wanted to write a super-set class with support for API's not conforming to REST

**Comment by TobiasHauck** [comment]
Can you show me how these APIs work? Our goal is to fully enable you to use each kind of REST API, so maybe we can work it this way out?

**Comment by Yuav** [comment]
For my particular case it's a SOAP API

**Comment by TobiasHauck** [comment]
ok this is really a case that doesn't fit semantically to this driver. To enable Doctrine supporting SOAP we need another driver which could maybe extend this one.

We should find out which properties really need to be accessible. The best way to proof it is you fork this repo and build the SOAP driver based on the fork. When this is done we do exactly know which properties need to be accessible. Do you think this is a good idea or do you have any other proposals?

**Pull request closed without merging**
